"""Database package"""

from app.db.client import (
    connect_db,
    create_feedback,
    create_model_metric,
    create_scan,
    create_threat,
    disconnect_db,
    get_all_config,
    get_client,
    get_config,
    get_feedback,
    get_feedback_by_scan,
    get_feedback_list,
    get_latest_model_metric,
    get_model_metrics,
    get_scan,
    get_scans,
    get_scans_by_confidence,
    get_scans_count,
    get_stats,
    get_threat,
    get_threats,
    set_config,
    update_feedback_status,
    update_threat_block_count,
)

__all__ = [
    "get_client",
    "connect_db",
    "disconnect_db",
    "create_scan",
    "get_scan",
    "get_scans",
    "get_scans_count",
    "get_scans_by_confidence",
    "create_feedback",
    "get_feedback",
    "get_feedback_by_scan",
    "get_feedback_list",
    "update_feedback_status",
    "get_config",
    "set_config",
    "get_all_config",
    "create_threat",
    "get_threat",
    "get_threats",
    "update_threat_block_count",
    "create_model_metric",
    "get_model_metrics",
    "get_latest_model_metric",
    "get_stats",
]